### ISSUE TITLE
Is there a good reason why register-http-mocks.js is in project root?

### ISSUE THREAD

**Issue by bcardarella** [jasonmit/ember-cli-testem-http-mocks#1]
This seems like a poor place to put this file. It would be better suited to be in `server/` rather than root. I also think a better overall approach can be made by exposing the mocks functionality as an exported named function rather than it a separate file. This would keep it in `server/index.js` and the change could be pushed upstream back into `ember-cli`'s blueprint. Thoughts?

**Comment by jasonmit** [comment]
Just acknowledging I read this, I'll need a day or two to track down a conversation I had with someone in the past as to why.  It may have been specific to the project I was working on at the time, so your concern could be valid.

**Comment by jasonmit** [comment]
I could not find the discussion, but I'm happy to accept a PR to move it out of the project root.

**Comment by bcardarella** [comment]
@jasonmit cool, thanks for considering it. I'll try to get one together soon

**Comment by jasonmit** [comment]
Had some time today to work on this, versioned as 0.3.0.  Be sure to re-run to generator `ember g ember-cli-testem-http-mocks` since I also folded `register-http-mocks` into `server/index`
